:concurrency: <%= ENV.fetch('SIDEKIQ_CONCURRENCY', 5) %>
:queues:
  - [default, 8]
  - [pull, 6]
  - [scheduler]

:scheduler:
  :listened_queues_only: true
:schedule:
  scheduled_statuses_scheduler:
    every: <%= ENV.fetch('UPDATE_ACCOUNT_STATUSES', "60m") %>
    class: Scheduler::UpdateAccountStatusesScheduler
    queue: scheduler
  user_statuses_scheduler:
    every: <%= ENV.fetch('USER_STATUSES', "60m") %>
    class: Scheduler::UpdateUserStatusesScheduler
    queue: scheduler
